version: 2.1
orbs:
  orb-tools: circleci/orb-tools@10.1.0
  uni-security-orb: uni-intelligence/uni-security-orb@0.3

workflows:
  lint:
    when: << pipeline.git.branch >>
    jobs:
      - orb-tools/lint:
          workspace-root: src
      - uni-security-orb/security_pack:
          context: build
          filters:
            branches:
              only:
                - main

  pack_and_publish:
    when: << pipeline.git.tag >>
    jobs:
      - orb-tools/pack:
          workspace-root: .
          filters: &filters_tags
            tags:
              only: /.*/
      - orb-tools/publish:
          name: Publish dev version
          context: uni-deploy-orb
          attach-workspace: true
          workspace-root: .
          orb-path: ./orb.yml
          orb-ref: uni-intelligence/asi-docker-buildx-orb@dev:<< pipeline.git.tag >>
          requires:
            - orb-tools/pack
          filters:
            tags:
              only: /\d+\.\d+\.\d+-rc.*/
      - orb-tools/publish:
          name: Publish
          context: uni-deploy-orb
          attach-workspace: true
          workspace-root: .
          orb-path: ./orb.yml
          orb-ref: uni-intelligence/asi-docker-buildx-orb@<< pipeline.git.tag >>
          requires:
            - orb-tools/pack
          filters:
            tags:
              only: /\d+\.\d+\.\d+/


  security_workflow:
    triggers:
      - schedule:
          cron: "0 0 * * 0"
          filters:
            branches:
              only:
                - main
    jobs:
      - uni-security-orb/security_pack:
          context: build
