description: >
  Build and tag a Docker image

parameters:
  step-name:
    type: string
    default: Docker build
    description: Specify a custom step name for this command, if desired

  dockerfile:
    type: string
    default: Dockerfile
    description: Name of dockerfile to use, defaults to Dockerfile

  path:
    type: string
    default: .
    description: >
      Path to the directory containing your Dockerfile and build context,
      defaults to . (working directory)

  lint-dockerfile:
    type: boolean
    default: false
    description: >
      Lint Dockerfile before building?

  treat-warnings-as-errors:
    type: boolean
    default: false
    description: >
      If linting Dockerfile, treat linting warnings as errors (would trigger
      an exit code and fail the CircleCI job)?

  registry:
    type: string
    default: docker.io
    description: >
      Name of registry to use, defaults to docker.io

  image:
    type: string
    description: Name of image to build

  tag:
    type: string
    default: $CIRCLE_SHA1
    description: Image tag, defaults to the value of $CIRCLE_SHA1

  cache_from:
    type: string
    default: ""
    description: >
      Images to consider as cache sources. Specified as comma separated values of
      image and tag syntax. An implicit `docker pull` will be done for each image
      specific to fetch the image. Thus, an explicit `docker pull` does not need
      to be done.
      For example, node:13,python:latest,openjdk:12,gcr.io/google-containers/busybox.
      Please see https://docs.docker.com/engine/reference/commandline/build/

  extra_build_args:
    type: string
    default: ""
    description: >
      Extra flags to pass to docker build. For examples, see
      https://docs.docker.com/engine/reference/commandline/build

  debug:
    type: boolean
    default: false
    description: >
      Extra output for orb developers

steps:
  - when:
      condition: <<parameters.lint-dockerfile>>
      steps:
        - dockerlint:
            treat-warnings-as-errors: <<parameters.treat-warnings-as-errors>>
            dockerfile: <<parameters.path>>/<<parameters.dockerfile>>
            debug: <<parameters.debug>>

  - run:
      name: <<parameters.step-name>>
      command: |
        IFS="," read -ra CACHE_FROM_IMAGES \<<< "<< parameters.cache_from >>"
        for image in "${CACHE_FROM_IMAGES[@]}"; do
          docker pull $image || echo "Failed to pull the specified image, $image. Ignoring..."
        done

        docker build \
          --cache-from "<<parameters.cache_from>>" \
          <<#parameters.extra_build_args>><<parameters.extra_build_args>><</parameters.extra_build_args>> \
          -f <<parameters.path>>/<<parameters.dockerfile>> -t \
          <<parameters.registry>>/<< parameters.image>>:<<parameters.tag>> \
          <<parameters.path>>
