description: >
  Configure a credentials store for docker to use.
  See: https://docs.docker.com/engine/reference/commandline/login/#credentials-store#credentials-store
  Supported platforms: Linux and macOS.

parameters:
  helper-name:
    description: >
      Name of the credential helper to be used, e.g. "pass".
      If left blank, the orb will attempt to choose one based on the platform.
    type: enum
    enum: ["", "pass", "osxkeychain"]
    default: ""
  docker-config-path:
    description: >
      Path to the Docker CLI config file.
    type: string
    default: $HOME/.docker/config.json

steps:
  - jq/install
  - run:
      name: Configure Docker credentials store
      command: |
        HELPER_NAME="<<parameters.helper-name>>"
        if [ -z "${HELPER_NAME}" ]; then
          if [ -n "$(uname | grep "Darwin")" ]; then
            HELPER_NAME="osxkeychain"
          else
            HELPER_NAME="pass"
          fi
        fi

        if [ ! -f "<<parameters.docker-config-path>>" ]; then
          echo "<<parameters.docker-config-path>> does not exist; initializing it.."
          mkdir -p $(dirname <<parameters.docker-config-path>>)
          echo "{}" > <<parameters.docker-config-path>>
        fi

        cat <<parameters.docker-config-path>> \
          | jq --arg credsStore "$HELPER_NAME" '. + {credsStore: $credsStore}' \
          > /tmp/docker-config-credsstore-update.json
        cat /tmp/docker-config-credsstore-update.json > <<parameters.docker-config-path>>
        rm /tmp/docker-config-credsstore-update.json
