description: >
  Install the `docker-compose` CLI. Supports stable versions.
  Requirements: curl, Docker, grep, jq, sha256sum,

parameters:
  version:
    type: string
    default: latest
    description: >
      Version of `docker-compose` to install, defaults to the latest stable release.
      If specifying a version other than latest, provide a full release tag,
      as listed at https://github.com/docker/compose/releases or
      https://api.github.com/repos/docker/compose/releases, e.g., `v2.10.0`.
      Only versions equal or above v2.0.1 are supported.

  install-dir:
    type: string
    default: /usr/local/bin
    description: >
      Directory in which to install `docker-compose`

steps:
  - run:
      name: Install docker-compose
      environment:
        PARAM_DOCKER_COMPOSER_VERSION: << parameters.version >>
        PARAM_INSTALL_DIR: <<parameters.install-dir>>
        SCRIPT_UTILS: <<include(scripts/utils.sh)>>
      command: <<include(scripts/install-docker-compose.sh)>>
